-- M5b 批 3：runs 表补挂起信息与产出/轨迹列（docs/24 §3.3/§4）。
-- 002 的 CREATE TABLE 已含这些列（新装库直接到位）；本迁移供已建旧表的库升级。
ALTER TABLE runs ADD COLUMN IF NOT EXISTS suspended_at TEXT;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS kind TEXT;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS node_id TEXT;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS deadline_at TEXT;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS resume_token TEXT;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS outputs JSONB;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS trace JSONB;
